[package]
name = "ll"
version = "0.1.0"
edition = "2021"
authors = [ "Go Erik <erkgo.eg@gmail.com" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
